---
- name: Adding users in host machines
  hosts: dev
  user: ansible
  become: yes
  tasks:
   - name: Adding 2 users in dev environment
     user:
      name: "{{ item }}"
      state: present
      groups: wheel
     loop:
      - testuser1
      - testuser2
  
