---
- name: Install httpd
  hosts: dev
  tasks:
  - name: Install httpd
    yum:
     name: "{{ ansible_facts['ansible_local']['httpd']['basic']['package'] }}"
     state: latest
  - name: start and enabled httpd
    service:
     name: "{{ ansible_facts['ansible_local']['httpd']['basic']['service'] }}"
     state: "{{ ansible_facts['ansible_local']['httpd']['basic']['state'] }}"
     enabled: "{{ ansible_facts['ansible_local']['httpd']['basic']['enabled'] }}"
