---
- name: Example of string type playbook variable
  hosts: dev
  vars:
   apache: httpd
   apache_root: /var/www/html
  tasks:
   - name: Installing httpd package
     yum: 
      name: "{{ apache }}"
      state: installed
   - name: Starting and Enabling the httpd package
     service:
      name: "{{ apache }}"
      state: started
      enabled: true
   - name: Creating "{{ apache_root }}" directory
     file: 
      path: "{{ apache_root }}"
      state: directory
   - name: Creating index.html page inside "{{ apache_root }}""
     copy:
      content: "Sandeep is a Devops Engineer"
      dest: "{{ apache_root }}/index.html"
