---
- name: Grouping the handlers 
  hosts: dev
  tasks:
  - name: Restart services on remote host
    command: echo "This tasks restart the service"
    notify: "service restart"

  handlers:
  - name: Restart Apache
    service:
     name: httpd
     state: restarted
    listen: "service restart"
  - name: Restart Rsyslog
    service:
     name: rsyslog
     state: restarted
    listen: "service restart"
