---
- name: Install Apache on RHEL server
  hosts: dev
  tasks:
  - name: Install the latest version of Apache
    yum:
     name: httpd
     state: latest
  - name: Configuring Apache
    copy:
     content: "Sandeep is a Devops Engineer in Amazon"
     dest: /var/www/html/index.html
     owner: apache
     group: apache 
     mode: 0644          
    notify: 
     - Configure Firewall  
     - Start Apache
  handlers:
  - name: Start Apache
    service:
     name: httpd
     state: started
  - name: Configure Firewall  
    firewalld:
     permanent: yes
     immediate: yes
     service: httpd
     state: enabled
