---
- name: Apache Webserver Configuration Playbook
  hosts: dev
  tasks:
   - name: Installing Apache Latest Packages
     yum:
      name: httpd
      state: latest
   - name: Starting and Enabling Apache httpd Service
     service:
      name: httpd
      state: started
      enabled: true
   - name: Setting up Apache Web Server
     template:
      src: /home/ansible/jinja/index.j2
      dest: /var/www/html/index.html
   - name: Restarting Apache httpd Service
     service:
      name: httpd
      state: restarted
