---
- name: Ansible template with filters example playbook
  hosts: dev
  tasks:
   - name: Using filters with jinja2 template
     template:
      src: /home/ansible/jinja/string.j2
      dest: /home/ansible/string.txt

