---
- name: block and resuce example
  hosts: all
  tasks:
   - block:
      - name: Installing the EPEL repository RPM
        command: sudo yum install -y https://dlll.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm 
      - name: Verify the EPEL repository file
        shell: ls /etc/yum.repos.d/epel.repo
     when: ansible_distribution_major_version == '9'
     rescue:
      - name: Copying EPEL repository file from the Ansible control node
        copy:
         src: /tmp/epel.repo
         dest: /etc/yum.repos.d/epel.repo
